version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
  #     - /usr/local/var/mysql:/var/lib/mysql

  # app:
  #   build: .
  #   entrypoint: sh -c "npm install && npm run start:dev"
  #   ports:
  #     - 3000:3000
  #   depends_on: 
  #     - "mysql"
  #   volumes:
  #     - .:/home/node/app